name: Build mastero

on: 

  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: master
  CONFIG_FILE: mastero.config
  CUSTOM_SH: custom.sh
  FILE_NAME: mastero

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y full-upgrade
        sudo -E apt-get -y install build-essential gawk gcc-multilib flex git gettext libncurses5-dev libssl-dev python3-distutils zlib1g-dev
        sudo -E apt-get -y autoremove
        sudo -E apt-get autoclean

    - name: Clone source code
      run: |
        git clone -b master --single-branch https://github.com/openwrt/openwrt.git openwrt
        cd openwrt
        git clone -b master --single-branch https://github.com/openwrt/luci.git luci

    - name: Update Install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configuration Customization
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./custom.sh && ./custom.sh
        cd openwrt && make defconfig

    - name: Download package
      run: |
        cd openwrt
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build firmware
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) V=s
 
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: $FILE_NAME
        path: openwrt/bin

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 3
        keep_minimum_runs: 1
