name: Build mastero

on: 

  repository_dispatch:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: master
  CONFIG_FILE: mastero.config
  CUSTOM_SH: custom.sh

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 检查
      uses: actions/checkout@master

    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y full-upgrade
        sudo -E apt-get -y install build-essential gawk gcc-multilib flex git gettext libncurses5-dev libssl-dev python3-distutils zlib1g-dev
        sudo -E apt-get -y autoremove
        sudo -E apt-get autoclean

    - name: 克隆源代码
      run: |
        git clone -b master --single-branch https://github.com/openwrt/openwrt.git openwrt
        cd openwrt
        git clone -b master --single-branch https://github.com/openwrt/luci.git luci

    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -a

    - name: 自定义配置文件
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $CUSTOM_SH
        cd openwrt
        $GITHUB_WORKSPACE/$CUSTOM_SH

    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
 
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: mastero
        path: openwrt/bin

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@master
      with:
        retain_days: 5
        keep_minimum_runs: 0
